name: master builder

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/master.yml'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
          - .
          - core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang env
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false # conflict with golangci-lint cache
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54
          working-directory: ${{ matrix.directory }}
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang env
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: go build
      - name: Unit Test
        run: go test -v $(go list ./... | grep -v /test) # skip e2e test
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang env
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Install Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Setup Teamgram Env
        run: |
          git clone https://github.com/teamgram/teamgram-server.git
          cd teamgram-server
          git checkout 5e85350a89e4cff66f54ad28175050f622f94fe5
          sudo docker compose -f ./docker-compose-env.yaml up -d --quiet-pull
      - name: Setup Docker Cache
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true
      - name: Setup Teamgram
        run: |
          cd teamgram-server
          sudo docker compose up -d --build
      - name: Build
        run: go build
      - name: E2E Test
        run: ginkgo -v -r ./test
